### ISSUE TITLE
async issue

### ISSUE THREAD

**Issue by jxcangel** [awadhn/robotframework-run-keyword-async#2]
I've some code is working well on 1.0.5, but not working on 1.0.6, here is error msg:

```
1253 20170809 18:10:23.789 - INFO - +-- START KW: runKeywordAsync.Wait Async All [ timeout=60 ]
1254 20170809 18:10:23.791 - INFO - +--- START KW: host.Send Shell Cmd [ device=<jnpr.toby.hldcl.system.System object at 0x113152160> | cmd=hostname ]
1255 20170809 18:10:23.797 - INFO - ================================ SEND_SHELL_CMD ================================
1256 20170809 18:10:23.798 - FAIL - AttributeError: 'str' object has no attribute 'shell'
1257 20170809 18:10:23.798 - DEBUG - Traceback (most recent call last):
1258   File "/usr/local/lib/python3.6/site-packages/jnpr/toby/utils/linux/linux_tool.py", line 64, in send_shell_cmd
1259     result = device.shell(command=host_cmd, timeout=options["timeout"]).response()
1260 20170809 18:10:23.798 - INFO - +--- END KW: host.Send Shell Cmd (14)
1261 20170809 18:10:23.805 - INFO - ================================ SEND_SHELL_CMD ================================
1262 20170809 18:10:23.806 - FAIL - AttributeError: 'str' object has no attribute 'shell'
1263 20170809 18:10:23.806 - DEBUG - Traceback (most recent call last):
1264   File "/usr/local/lib/python3.6/site-packages/jnpr/toby/utils/linux/linux_tool.py", line 64, in send_shell_cmd
1265     result = device.shell(command=host_cmd, timeout=options["timeout"]).response()
1266 20170809 18:10:23.806 - INFO - +--- END KW: host.Send Shell Cmd (15)
1267 20170809 18:11:23.793 - INFO - Log level changed from NONE to INFO.
```

And here is robot code:

```
    # Run async keyword to get response from different device.
    ${hdl_1}    Run Keyword Async   host.send shell cmd     device=${h0}        cmd=hostname
    ${hdl_2}    Run Keyword Async   host.send shell cmd     device=${h1}        cmd=hostname
    ${list_response}    Wait Async All      timeout=60
    ${h0_response}      Get Async Return    ${hdl_1}
    ${h1_response}      Get Async Return    ${hdl_2}
```

Due to my investigation, 1.0.5 use threading module but 1.0.6 is multiprocessing? I think this is root cause of my failure

**Comment by awadhn** [comment]
Yes, we had to move to multiprocessing to achieve true parallelism hence you can not pass/share device handles. The way we are handling in our case is, by creating device handle inside keyword we invoking as child process.
